name: Run DynamoRIO

on:
  push:

jobs:
  run-drmemory:
    name: '${{ matrix.os }} + ${{ matrix.arch }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        arch: [armv7, aarch64, x64, x86, mips, mips64]
        
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          ref: 1977c00f00ad0546421a5ec0b40c1326aee4cddb
          
      - name: Build repository 
        run: | 
          ./Configure && make
        continue-on-error: true 

      - name: Install DynamoRIO
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update
          sudo apt-get install -y libunwind8
          wget -P /tmp/ https://github.com/DynamoRIO/dynamorio/releases/download/release_10.0.0/DynamoRIO-Linux-10.0.0.tar.gz && tar -xzf /tmp/DynamoRIO-Linux-10.0.0.tar.gz -C /tmp/
           
      - name: Disable Address Space Randomization
        if: runner.os == 'Linux'
        run: sudo sysctl -w kernel.randomize_va_space=0
      
      - name: Disable swapping 
        if: runner.os == 'Linux' 
        run: sudo swapoff -a
        
      - name: Run DynamoRIO (Code Coverage)
        run: |
          export DYNAMORIO_HOME="/tmp/DynamoRIO-Linux-10.0.0"
          export GITHUB_PATH="$DYNAMORIO_HOME/bin64:$DYNAMORIO_HOME/tools/bin64:$GITHUB_PATH"
          export LD_LIBRARY_PATH="$DYNAMORIO_HOME/lib64:$LD_LIBRARY_PATH"
          #!/bin/bash
          set +e 

          echo "=========[DynamoRIO Service Started!]========="

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_dynrio_coverage() {
            local executable="$1"
            local log_dir="./logs_coverage"
            mkdir -p "$log_dir"
            $DYNAMORIO_HOME/bin64/drrun -t drcov -logdir "$log_dir" -dump_text -- "$executable"
            local exit_status=$?
            
            if [ $exit_status -eq 124 ]; then
              echo "Execution timed out after 45 seconds: $executable"
            fi

            for log_file in "$log_dir"/drcov.*.log; do
              $DYNAMORIO_HOME/tools/bin64/drcov2lcov -input "$log_file" -src_filter "$log_dir"
            done
          }
          
          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_dynrio_coverage "$file"
              echo ""
              echo ""
            fi
          done

          echo "=========[DynamoRIO service finished]========="

      - name: Run DynamoRIO (Cachesim)
        run: |
          export DYNAMORIO_HOME="/tmp/DynamoRIO-Linux-10.0.0"
          export GITHUB_PATH="$DYNAMORIO_HOME/bin64:$DYNAMORIO_HOME/tools/bin64:$GITHUB_PATH"
          export LD_LIBRARY_PATH="$DYNAMORIO_HOME/lib64:$LD_LIBRARY_PATH"
          #!/bin/bash
          set +e 

          echo "=========[DynamoRIO Service Started!]========="

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_dynrio_cachesim() {
            local executable="$1"
            local log_dir="./logs_cachesim"
            mkdir -p "$log_dir"
            $DYNAMORIO_HOME/bin64/drrun -t drcachesim -- "$executable" > "${log_dir}/${basename executable}-drcachesim.log" 2>&1
            local exit_status=$?
            
            if [ $exit_status -eq 124 ]; then
              echo "Execution timed out after 45 seconds: $executable"
            fi

            for log_file in "$log_dir"/drcov.*.log; do
              $DYNAMORIO_HOME/tools/bin64/drcov2lcov -input "$log_file" -src_filter "$log_dir"
            done
          }
          
          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_dynrio_cachesim "$file"
              echo ""
              echo ""
            fi
          done

          echo "=========[DynamoRIO service finished]========="
          
      - name: Run DynamoRIO (Memtrace)
        run: |
          export DYNAMORIO_HOME="/tmp/DynamoRIO-Linux-10.0.0"
          export GITHUB_PATH="$DYNAMORIO_HOME/bin64:$DYNAMORIO_HOME/tools/bin64:$GITHUB_PATH"
          export LD_LIBRARY_PATH="$DYNAMORIO_HOME/lib64:$DYNAMORIO_HOME/tools/lib64/release:$LD_LIBRARY_PATH"
          #!/bin/bash
          set +e 

          echo "=========[DynamoRIO Memtrace Service Started!]========="
          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_dynrio_memtrace() {
            local executable="$1"
            local log_dir="./logs_memtrace"
            mkdir -p "$log_dir"
            $DYNAMORIO_HOME/bin64/drrun -c samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool TLB -- "$executable" > "${log_dir}/${executable}-TLB.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool reuse_distance -reuse_distance_histogram -- "$executable" > "${log_dir}/${basename executable}-reuse_dist.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool reuse_time -- "$executable" > "${log_dir}/${basename executable}-reuse_time.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool basic_counts -- "$executable" > "${log_dir}/${basename executable}-basic_counts.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool opcode_mix -- "$executable" > "${log_dir}/${basename executable}-opcodemix.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool view -- "$executable" > "${log_dir}/${basename executable}-view.log" 2>&1
            $DYNAMORIO_HOME/bin64/drrun -t samples/bin64/libmemtrace_x86_text.so -offline -logdir "$log_dir" -tool histogram -- "$executable" > "${log_dir}/${basename executable}-histogram.log" 2>&1
          }
          
          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_dynrio_memtrace "$file"
              echo ""
              echo ""
            fi
          done

          echo "=========[DynamoRIO Memtrace service finished]========="

      - name: Run DynamoRIO (CPU Simulator)
        run: |
          export DYNAMORIO_HOME="/tmp/DynamoRIO-Linux-10.0.0"
          export GITHUB_PATH="$DYNAMORIO_HOME/bin64:$DYNAMORIO_HOME/tools/bin64:$GITHUB_PATH"
          export LD_LIBRARY_PATH="$DYNAMORIO_HOME/lib64:$LD_LIBRARY_PATH"
          #!/bin/bash
          set +e 

          echo "=========[DynamoRIO CPU Sim Service Started!]========="
          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_dynrio_cpusim() {
            local executable="$1"
            local log_dir="./logs_cpusim"
            mkdir -p "$log_dir"
            cpus=("Pentium" "PentiumMMX" "PentiumPro" "Pentium2" "Klamath" "Deschutes" "Pentium3" "Coppermine" "Tualatin" "PentiumM" "Banias" "Dothan" "Willamette" "Northwood" "Pentium4" "Prescott" "Presler" "Core2" "Merom" "Penryn" "Nehalem" "Westmere" "Sandybridge" "Ivybridge")
            for cpu in "${cpus[@]}"; do
                local log_file="${log_dir}/${basename executable}-ran-on-${cpu}.log"
                timeout --signal=SIGQUIT 30s $DYNAMORIO_HOME/bin64/drrun -t drcpusim -continue -ignore_all_libs -cpu "$cpu" -- "$executable" > "$log_file" 2>&1
            done
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_dynrio_cpusim "$file"
              echo ""
              echo ""
            fi
          done

          echo "=========[DynamoRIO CPU Sim service finished]========="
          
      - name: Upload DynamoRIO reports (for Code Coverage)
        uses: actions/upload-artifact@v4
        with:
          name: dynamoRIO_codecoverage-report-${{ github.event.repository.name }}-on-${{ matrix.os }}-under-${{ matrix.arch }}
          path: './logs_coverage/*'

      - name: Upload DynamoRIO reports (for Cache Simulator)
        uses: actions/upload-artifact@v4
        with:
          name: dynamoRIO_cachesim-report-${{ github.event.repository.name }}-on-${{ matrix.os }}-under-${{ matrix.arch }}
          path: './logs_cachesim/*'

      - name: Upload DynamoRIO reports (for Memtrace)
        uses: actions/upload-artifact@v4
        with:
          name: dynamoRIO_memtrace-report-${{ github.event.repository.name }}-on-${{ matrix.os }}-under-${{ matrix.arch }}
          path: './logs_memtrace/*'
  
      - name: Upload DynamoRIO reports (for CPU Simulator)
        uses: actions/upload-artifact@v4
        with:
          name: dynamoRIO_cpusim-report-${{ github.event.repository.name }}-on-${{ matrix.os }}-under-${{ matrix.arch }}
          path: './logs_cpusim/*'
